version: '3'

networks:
  net:

services:
  appl:
    build: ..
    ports:
      - 8080:8080
    env_file: .env
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - net

  db:
    image: library/postgres:13.2
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
    restart: on-failure
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - net

  db_ui:
    image: dpage/pgadmin4:5.1
    environment:
      PGADMIN_DEFAULT_EMAIL: void@domain.tld
      PGADMIN_DEFAULT_PASSWORD: void
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 8081:80
    networks:
      - net

